---
  
- name: Install Pinghouse CLI tools
  homebrew: name={{ item }} state=latest
  with_items:
    - unison

- name: Install Pinghouse apps
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - drobo-dashboard
    - plex-home-theater
    - teamviewer
    - tigervnc-viewer

- name: Add automation scripts
  copy: src={{ item }} dest=~/Documents/Automation/Scripts/ mode=0755
  with_fileglob: Automation/Scripts/*
