---

- name: Tap external homebrew repos
  homebrew_tap: name={{ item }} state=present
  with_items:
    - homebrew/php

- name: Install dev CLI apps
  homebrew: name={{ item }} state=installed
  with_items:
    - git
    - git-flow
    - mysql
    - python
    - php56
    - php56-xdebug
    - sqlite
    - subversion

- name: Install dev applications
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - phpstorm
    - pycharm
    - sequel-pro
    - vagrant
    - virtualbox
    - vmware-fusion

- name: Copy dotfiles
  copy: src={{ item }} dest=~/{{ item }}
  with_items:
    - .gitconfig
    - .profile
