---

- name: Tap external homebrew repos
  homebrew_tap: name={{ item }} state=present
  with_items:
    - homebrew/php
    - homebrew/apache

- name: Install httpd
  homebrew: name=httpd22 state=installed

- name: Install PHP
  homebrew: name=php56 install_options=with-apache,homebrew-apxs state=installed

- name: Install dev CLI apps
  homebrew: name={{ item }} state=installed
  with_items:
    - composer
    - git
    - git-flow
    - mercurial
    - mysql
    - nmap
    - pandoc
    - python
    - php56-apcu
    - php56-mcrypt
    - php56-xdebug
    - sqlite
    - subversion

- name: Install dev applications
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - phpstorm
    - pycharm
    - sequel-pro
    - vagrant
    - virtualbox
    - vmware-fusion
    - xquartz

- name: Install python packages
  pip: name={{ item }} state=present
  with_items:
    - beautifulsoup4
    - virtualenv

- name: Copy dotfiles
  copy: src={{ item }} dest=~/{{ item }}
  with_items:
    - .gitconfig
    - .profile

- name: Copy httpd.conf
  copy: src=httpd.conf dest=/usr/local/etc/apache2/2.2/httpd.conf

- name: Copy php.ini
  copy: src=php.ini dest=/usr/local/etc/php/5.6/php.ini
  
- name: Install vagrant plugins
  command: vagrant plugin install vagrant-hostsupdater

- name: Install terminal themes
  command: "open '{{ item }}'"
  with_fileglob: "*.terminal"
