---

- name: Tap external homebrew repos
  homebrew_tap: name={{ item }} state=present
  with_items:
    - homebrew/php
    - homebrew/apache
    - homebrew/services

- name: Install httpd
  homebrew: name=httpd22 state=latest

- name: Install PHP
  homebrew: name=php56 install_options=with-apache,homebrew-apxs state=latest

- name: Install dev CLI apps
  homebrew: name={{ item }} state=latest
  with_items:
    - composer
    - git
    - git-flow
    - mercurial
    - mysql
    - nmap
    - pandoc
    - python
    - php56-apcu
    - php56-mcrypt
    - php56-xdebug
    - sqlite
    - subversion

- name: Install dev applications
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - phpstorm
    - pycharm
    - sequel-pro
    - vagrant
    - virtualbox
    - vmware-fusion
    - xquartz

- name: Install python packages
  pip: name={{ item }} state=latest
  with_items:
    - beautifulsoup4
    - virtualenv

- name: Copy dotfiles
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - gitconfig
    - profile

- name: Create .ssh directory
  file: path=~/.ssh state=directory

- name: Touch SSH config file
  file: path=~/.ssh/config state=touch

- name: Configure apache to run as user
  replace: dest="{{ httpd_conf }}" regexp="^User .+$" replace="User {{ ansible_ssh_user }}"

- name: Add index.php to apache index files
  replace: dest="{{ httpd_conf }}" regexp="^(\s*)DirectoryIndex index.html$" replace="\1DirectoryIndex index.html index.php"

- name: Add apache PHP handler
  lineinfile: dest="{{ httpd_conf }}" line="AddHandler php5-script .php"

- name: Add apache PHP handler
  lineinfile: dest="{{ httpd_conf }}" line="AddType text/html .php"

- name: Create apache conf.d directory
  file: path={{ httpd_confd }} state=directory

- name: Apache configuration for dev directory
  template: src=httpd_confd/dev.conf dest={{ httpd_confd }}/dev.conf

- name: Add xdebug section to php.ini
  lineinfile: dest={{ php_ini }} line=[xdebug] state=present insertbefore="; Local Variables:"
  tags: test

- name: Enable xdebug in php.ini
  lineinfile: dest={{ php_ini }} line="xdebug.remote_enable = 1" state=present insertafter="\[xdebug\]"
  tags: test

- name: Create dev directory
  file: path={{ home_dir }}/dev state=directory

- name: Symlink webroot to dev
  file: src={{ home_dir }}/dev dest={{ htdocs_dir }}/dev state=link force=yes

- name: Create phpinfo page
  copy: src=info.php dest={{ htdocs_dir }}/info.php owner={{ ansible_ssh_user }}
  
- name: Copy test scripts
  copy: src=test dest={{ home_dir }}/dev

- name: Install vagrant plugins
  command: vagrant plugin install vagrant-hostsupdater

- name: Install terminal themes
  command: "open '{{ item }}'"
  with_fileglob: "*.terminal"

- name: Start apache
  command: brew services restart httpd22

- name: Start mysql
  command: brew services restart mysql
